dataset:
  name: CIFAR10
  root: "C:\Users\delga\Documents\programming\datasets"
  batch_size: 128

training:
  epochs: 5
  learning_rates: [0.01, 0.005, 0.001]
  weight_decays: [0.001, 0.0001]
  dropouts: [0.25, 0.3, 0.4]

model:
   name: "CNN"
   dropout: 0.25

device: "cuda"